### ISSUE TITLE
Artic_vcf_merge failed

### ISSUE THREAD

**Issue by idolawoye** [artic-network/fieldbioinformatics#103]
Hi, I am getting the following error when I run the minion command:

`Command failed:artic_vcf_merge CERI-KRISP-K032245_ONT /home/idowu/Downloads/Bioinfo/fieldbioinformatics/test-data/primer-schemes/nCoV-2019/V3/nCoV-2019.scheme.bed 2> CERI-KRISP-K032245_ONT.primersitereport.txt nCoV-2019_2:CERI-KRISP-K032245_ONT.nCoV-2019_2.vcf nCoV-2019_1:CERI-KRISP-K032245_ONT.nCoV-2019_1.vcf
`

The command I entered was:

`artic minion --threads 10 --normalise 200 --skip-nanopolish --scheme-directory ~/Downloads/Bioinfo/fieldbioinformatics/test-data/primer-schemes --strict --read-file ../CERI-KRISP-K032245_ONT.fastq.gz nCoV-2019/V3 CERI-KRISP-K032245_ONT`

I don't know what seems to be wrong here

**Comment by BioWilko** [comment]
That's because without using nanopolish or medaka there is no variant caller in the pipeline therefore no vcf files to merge.

If you do not have access to the fast5 files I suggest you use the command:

`artic minion --threads 10 --normalise 200 --medaka --medaka-model <insert medaka model here> --scheme-directory ~/Downloads/Bioinfo/fieldbioinformatics/test-data/primer-schemes --strict --read-file ../CERI-KRISP-K032245_ONT.fastq.gz nCoV-2019/V3 CERI-KRISP-K032245_ONT`

[ONTs medaka repo explains how to determine your medaka model ](https://github.com/nanoporetech/medaka)

**Comment by idolawoye** [comment]
Thnaks!
