### ISSUE TITLE
Can the Artic pipeline be used if all the primers are in a single pool?

### ISSUE THREAD

**Issue by jonbra** [artic-network/fieldbioinformatics#139]
Hi,
If one has primers developed by PrimalScheme that follow the correct format for the Artic Pipeline, but pooled them all in a single tube for the PCR reaction, can the data still be analyzed with the pipeline? There will likely be reads/amplicons spanning multiple amplicons (super amplicons), and these will not have the expected left and right primers. 

Thanks,

Jon

**Comment by BioWilko** [comment]
Was this scheme designed as a single pool by primalscheme? If not combining the pools is very likely to break things due to primer interactions etc since pools are by definition designed to be amplified separately.

But assuming this scheme was designed as a single pool with overlap regions I think you're far more likely to get preferential amplification of short products (L primer of amplicon2, R primer of amplicon 1 for example) due to PCR bias so I think this is quite a bad idea unless you really know what you're doing.

BUT if you want to analyse a single pool overlapping amplicon scheme in field you can do so by ensuring that the bed file properly states that all primers belong to a single pool, this would chuck out any short products (such as my example above) due to having mismatched primers.

**Comment by jonbra** [comment]
Thanks! 
Just to make sure I understand correctly, you mean that I just write the number "1" for example in column 5 in the primer bed file do designate all primers to the same pool? Can I still use different numbers for each primer pair in the primer names? E.g. "primer_1_LEFT", "primer_1_RIGHT", "primer_2_LEFT", etc?

**Comment by BioWilko** [comment]
Yes the pool number is what will need to change, I will re-iterate that I do think that this isn't a great idea though.

**Comment by joshquick** [comment]
You do sometimes see amplicons from 1L to 3R etc within the same pool even with the standard approach. I think these currently get filtered out by a length filter in the first stage.

Are you thinking about doing something like the Swift Biosciences SNAP approach? I'd like to understand more about how that works.

**Comment by joshquick** [comment]
Yeah I did have a bit of trawl through their patents earlier and as you say they just pool the overlapping primers together. The small amplicons generated can either be cleaned up before 2nd round PCR or drop out due to suppression PCR if you add a common sequencing to the 5' end.

Anyway - I think trimming after mapping is the way to go as you say.
