### ISSUE TITLE
Longshot VCF causing bcftools to crash 

### ISSUE THREAD

**Issue by Mattstorey** [artic-network/fieldbioinformatics#21]
Hi,

Since the introduction of Longshot to the artic minion pipeline, I am seeing some genomes won't assemble. Seems like the VCF from Longshot doesn't match the reference (preconsensus.fasta) passed to `bcftools consensus` and causes an error resulting in an empty consensus.fasta file.

**Comment by nickloman** [comment]
Thank you - this happens when a variant passes in one pool and fails in another (typically due to low depth) meaning it gets written to both pass and fail and therefore gets masked and upsets bcftools consensus. I have made this update to the code which means that the variant will no longer get written to fail:
https://github.com/artic-network/fieldbioinformatics/pull/22

**Comment by Mattstorey** [comment]
Thanks, Nick! Awesome.

**Comment by lpmor22** [comment]
Hi,

I using the artic minion pipeline now and I'm having the same issue - some genomes won't assemble. 
I alreary updated using: pip install --force-reinstall git+https://github.com/artic-network/fieldbioinformatics.git but isn't work.
