### ISSUE TITLE
read depth plot bug/feature?

### ISSUE THREAD

**Issue by jvolkening** [artic-network/fieldbioinformatics#51]
I happened to examine one of the amplicon read depth plots (e.g. `sample-barplot.png`) that the ARTIC pipeline produces during some troubleshooting, and noticed that the reported read depths appear to be about half of that expected based on the values in the depth files (e.g. `sample.coverage_mask.txt.nCoV-2019_1.depths`). In looking at the code for the plotting script added back in May:

```python
amplicons = sorted(rgAmplicons[rg])
starts = sorted(rgStarts[rg])

# bin read depths by amplicon for this readgroup
df['amplicon'] = pd.cut(
    x=df['position'], bins=starts, labels=amplicons)

# store the mean of each bin
bins = (df.groupby(['amplicon'])[
        'depth'].mean()).rename(depthFile.name)
```
...it seems like this is taking the mean of the depths between each start position, but wouldn't this include the adjacent amplicon in the opposite read group (which would be all zeros). If so, this would explain why the values are about half those expected.

Sorry if I'm missing something obvious here.

**Comment by will-rowe** [comment]
Hi @jvolkening - yes that's exactly what it's doing. It's not ideal; I wrote it to quickly spot amplicon drop out rather than report depths from the depth file. It should really ignore the adjacent amplicon from the other readgroup, as you point out.

Hopefully I'll get around to improving this soon (although PR would be welcome if you fancy it). Cheers.

**Comment by jvolkening** [comment]
Okay, thanks for confirming. I'll put together a PR if I have some free time but it's not a priority (probably not for you either).
